# including modules

OBJS += $(BUILD)/BF_Implementation.o
OBJS += $(BUILD)/SL_Implementation.o
OBJS += $(BUILD)/HT_Implementation.o
OBJS += $(BUILD)/List_Implementation.o
OBJS += $(BUILD)/FM_Implementation.o
OBJS += $(BUILD)/MonitorManager.o



# including utilities
OBJS += $(BUILD)/hash_functions.o
OBJS += $(BUILD)/utilities.o
OBJS += $(BUILD)/file_utilities.o
OBJS += $(BUILD)/struct_manipulation.o
OBJS += $(BUILD)/TTY_API.o
OBJS += $(BUILD)/IPC.o
OBJS += $(BUILD)/networking.o
